export const TYPE_NAME_MAP: Record<string, string> = {
  fire: "Fuego",
  water: "Agua",
  grass: "Planta",
  electric: "Eléctrico",
  psychic: "Psíquico",
  rock: "Roca",
  fairy: "Hada",
  poison: "Veneno",
  fighting: "Lucha",
  ground: "Tierra",
  flying: "Volador",
  normal: "Normal",
  bug: "Bicho",
  ghost: "Fantasma",
  steel: "Acero",
  dragon: "Dragón",
  dark: "Siniestro",
  ice: "Hielo",
};

export const SPANISH_TO_ENGLISH_TYPE: Record<string, string> = {
  Fuego: "fire",
  Agua: "water",
  Planta: "grass",
  Eléctrico: "electric",
  Psíquico: "psychic",
  Roca: "rock",
  Hada: "fairy",
  Veneno: "poison",
  Lucha: "fighting",
  Tierra: "ground",
  Volador: "flying",
  Normal: "normal",
  Bicho: "bug",
  Fantasma: "ghost",
  Acero: "steel",
  Dragón: "dragon",
  Siniestro: "dark",
  Hielo: "ice",
  Todos: "all",
};
